spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=TEST
    username: sa
    password: Initial0
    hikari:
      maximumPoolSize: 3
    initialization-mode: always
jpa:
  hibernate:
    ddl-auto: create-drop
