spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    hikari:
      maximumPoolSize: 3
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create