server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  session:
    timeout: 120s
  servlet:
    session:
      timeout: 120s
spring:
  application:
    name: gate
  cloud:
    gateway:
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
      discovery:
         locator:
            enabled: true
      routes:
      - id: noti
        uri: http://localhost:8001
        predicates:
        - Path=/test/** 
        filters:
        - JwtRequestFilter
        - RemoveRequestHeader=Cookie
        - JwtResponseFilter
#        - RemoveResponseHeader=WWW-Authenticate
logging:
  level:
    org.springframework.web.reactive.DispatcherHandler: DEBUG
       
  