spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximumPoolSize: 3
    initialization-mode: always
 #   separator: ^
 #   continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE      