spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=US03
    username: sa
    password: 12345678
    hikari:
      maximumPoolSize: 3
    initialization-mode: always
  flyway:
    check-location: false
    baseline-on-migrate: true