spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximumPoolSize: 3
    initialization-mode: always
  jpa:
    generate-ddl: true
logging:
  level:
    root: INFO
