server:
  port: 8888
logging:
  level:
    org.springframework.web.reactive.DispatcherHandler: DEBUG
       
       
---
spring:
  profiles: dev       
  resources:
    static-locations: 
    - classpath:/static
    - file:../spring-cloud-gateway-static
  cloud:
    gateway:
      routes:
      - id: webx
        uri: http://localhost:8888
        predicates:
        - Path=/webx/** 
        filters:
          - StripPrefix=1
