spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?
    username: root
    password: 1234
    hikari:
      maximumPoolSize: 3
    initialization-mode: always
    continue-on-error: true