spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
#    username: root
#    password: 1234
    url: jdbc:sqlserver://localhost;databaseName=test;user=sa;password=12345678;
    hikari:
      maximumPoolSize: 3
logging:
  level:
    root: INFO
