server:
spring:
  datasource:
    url: jdbc:sap://10.59.62.103:30013/?databaseName=DBA&user=SYSTEM&password=Initial0&currentSchema=US_I058549_2694_05_29
mybatis:
  typeAliasesPackage: domain
  mapperLocations: classpath:mapper/*.xml